FROM --platform=linux/s390x ubuntu:24.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      cmake \
      g++ \
      pkg-config \
      libflint-dev \
      catch2 && \
    rm -rf /var/lib/apt/lists/*

