name: Big-endian Tests
description: Verify the library works on big-endian compilation/execution target
on: push
# TODO: re-institute
# on:
#   pull_request:
#   push:
#     branches: main
jobs:
  build-big-endian:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: s390x
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Build big-endian test image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${GITHUB_WORKSPACE}/.github/workflows/scripts/Dockerfile.big-endian
          platforms: linux/s390x
          tags: big-endian-tests:s390x
          load: true
          cache-from: type=gha,scope=big-endian-tests
          cache-to: type=gha,mode=max,scope=big-endian-tests

      # TODO: is this needed?
      - name: permissions
        run: chmod +x "${GITHUB_WORKSPACE}/.github/workflows/scripts/test-big-endian.sh"

      - name: Build and test
        run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/test-big-endian.sh
